spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=username
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080
